package com.carolinasanchez;
/*
BLACKJACK CONSOLE GAME PSEUDO CODE:

- REASSIGN THE VALUE OF J, Q, AND K TO 10.

- IF AN ACE IS IN THE HAND AND THE OTHER CARDS + 11 IS GREATER THAN 21, THEN THE VALUE OF THE ACE SHOULD BE REASSIGNED TO 1.

- CARD SUITS ARE: SPADES, CLUBS, DIAMONDS AND HEARTS. BUT WHAT ARE THE RANKS???

- CREATE ENUMS FOR SUIT AND RANK WITHIN THE CARD CLASS.

- WILL NEED SEVERAL ARRAYS: ONE FOR THE DECK, WITH SUB-ARRAYS CONSISTING OF THE DIFFERENT SUITS (REPRESENTED AS FOUR SUB-ARRAYS WITH THE CARDS A-K?). ANOTHER ARRAY FOR THE PLAYER'S HAND. ANOTHER ARRAY FOR THE DEALER'S HAND.

- WHEN CARDS ARE DEALT, THEY MOVE FROM THE DECK SUB-ARRAY THEY'RE IN TO THE PLAYER'S OR DEALER'S HAND, SO THAT THE SAME CARD CAN'T BE DRAWN TWICE.

- DRAW THE CARDS USING A RANDOM NUMBER GENERATOR, SO THAT THE CARDS DRAWN ARE RANDOM BUT THE DECK DOESN'T NEED TO BE SHUFFLED.

- IF THE DECK IS EMPTY AND A DRAW IS ATTEMPTED, DISPLAY THE MESSAGE THAT SORRY, THE DECK IS EMPTY? HOWEVER, WITH JUST TWO PLAYERS AND THE DESIRED NUMBER BEING 21, IT'S UNLIKELY THIS WOULD EVER HAPPEN?

- ADD PROMPTS AND SCANNERS TO REQUEST NAME AND BET AMOUNT FROM THE PLAYER.

- ACTOR INTERFACE FOR DEALER/PLAYER WITH THESE METHODS: GETNAME(), GETBALANCE(), GETBET(), GETACTION(VALUE - HIT OR STAY) - CARD INTERFACE CLASS?.

- AN INSTANCE OF THE PLAYER IN THE ACTOR INTERFACE CONTROLS THE USER'S ACTIONS.

- THE USER CAN HIT OR STAY WHEN IT'S THEIR TURN, THEY CAN KEEP HITTING UNTIL THEY DECIDE TO STAND OR THEIR HAND GOES BUST BY TOTALING OVER 21 POINTS.

- AN INSTANCE OF THE DEALER IN THE ACTOR INTERFACE CONTROLS THE DEALER'S ACTIONS. WHEN IT'S THEIR TURN, THEY MUST HIT IF THE TOTAL VALUE OF THEIR HAND IS 16 OR BELOW. IF IT'S 17 OR ABOVE, THEY CAN HIT OR STAND AT RANDOM. THEIR TURN ENDS IF THEY STAND OR BUST. THE PLAYER WINS IF THE DEALER BUSTS FIRST OR HAS A HAND THAT TOTALS FEWER POINTS THAN THEM (AS LONG AS THEY DON'T BUST).

*/
public class Main {

    public static void main(String[] args) {
	// write your code here
    }
}
